/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Watch = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const ContactRequest = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addWatch' : IDL.Func([Watch], [], []),
  'getAllContactRequests' : IDL.Func([], [IDL.Vec(ContactRequest)], ['query']),
  'getAllWatches' : IDL.Func([], [IDL.Vec(Watch)], ['query']),
  'getRequest' : IDL.Func([IDL.Text], [ContactRequest], ['query']),
  'getWatch' : IDL.Func([IDL.Text], [Watch], ['query']),
  'submitContactRequest' : IDL.Func([ContactRequest], [], []),
  'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Watch = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ContactRequest = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addWatch' : IDL.Func([Watch], [], []),
    'getAllContactRequests' : IDL.Func(
        [],
        [IDL.Vec(ContactRequest)],
        ['query'],
      ),
    'getAllWatches' : IDL.Func([], [IDL.Vec(Watch)], ['query']),
    'getRequest' : IDL.Func([IDL.Text], [ContactRequest], ['query']),
    'getWatch' : IDL.Func([IDL.Text], [Watch], ['query']),
    'submitContactRequest' : IDL.Func([ContactRequest], [], []),
    'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };